language: python

python:
    - "3.6"
install:
    - pip install "setuptools>=38.3"
    - "pip install flake8"
    - pip install ".[testing]"
before_script: "flake8 src --ignore=E501,W504,W503"
script:
    - pytest


branches:
  only:
  - master
  - dev
