language: python

python:
  - "3.8"
before_install:
  - pip install poetry
install:
  - poetry install

before_script:
  - "poetry run black --check brew_tools"
  - "poetry run flake8 brew_tools --ignore=E501,W504,W503"

script:
  - poetry run pytest tests

branches:
  only:
    - master
    - dev
