---
name: tests

"on":
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.24"

      - name: Setup Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install project
        run: uv sync --all-extras --dev

      - name: Tests
        run: uv run pytest tests

      - name: Lint
        run: rye run ruff check src tests

      - name: Format
        run: uv run ruff format --check src tests
